### PR TITLE
Fix counting using trait as logical line

### PR DESCRIPTION
**Pull request by kubawerlos**
Fixes https://github.com/sebastianbergmann/phploc/issues/209

### CODE REVIEW

**Comment by kubawerlos** [comment]
@sebastianbergmann what happened to CI? I saw you removed Travis config? Are you planning to change to Github Actions?

**Comment by kubawerlos** [comment]
Ping @sebastianbergmann

**Comment by sebastianbergmann** [comment]
I deactivated Travis integration for all of my projects. The plan is to move to GitHub actions.

**Comment by sebastianbergmann** [comment]
This branch now has conflicts that must be resolved.

**Comment by kubawerlos** [comment]
@sebastianbergmann done, ready for review

**Pull request merged**
