### PR TITLE
Fixes #111

### LINKED ISSUE #111: Average-metrics missing in xml/csv result
It seems as if at least some "average" metrics are missing in phploc xml- or csv-result.

I am using phploc 2.1.1. I pasted [console-output](http://pastebin.com/zXYukEJq),  [xml-output](http://pastebin.com/rSEu9DF6) and [csv-output](http://pastebin.com/kQ3aZkaT) on pastebin.

As far as I can see
- "Average Function Length" (from console) is missing in xml output. 
- "Average Class Length" and "Average Method Length" (from console) is missing in csv output. 
- "Average Complexity per LLOC", "Average Complexity per Class" and "Average Complexity per Method" seem to be missing both in xml- and csv-output.

### PR DESCRIPTION
**Pull request by SchulteMarkus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Needs to be one commit.

**Comment by sebastianbergmann** [comment]
Why do you think it must be one commit, @GrahamCampbell?

**Comment by ravage84** [comment]
@SchulteMarkus , what @GrahamCampbell probably meant was he would prefer to see a clean(er) commit history. Which I agree is generally a good thing.

> A clean commit history is one where each commit is a solid piece of work, representing a milestone in your feature or fix. This might be the backend for some part of the feature, or a component of the UI. It doesn’t have to be a large amount of work, just some good chunk that, conceptually, stands alone.

https://www.reviewboard.org/docs/codebase/dev/git/clean-commits/

Hope this helps you to clean it up:

https://www.atlassian.com/git/tutorials/rewriting-history/

**Comment by GrahamCampbell** [comment]
Yeh. Not necessarily one, but not 10...

**Comment by SchulteMarkus** [comment]
Thanks for the hints, @ravage84 - I will find some time to cleanup the commit history until Friday, hopefully.

**Comment by SchulteMarkus** [comment]
I have rewritten history in a new branch [bug/111_csv-misses-some-metrics](https://github.com/SchulteMarkus/phploc/tree/bug/111_csv-misses-some-metrics) at my [phploc-fork](https://github.com/SchulteMarkus/phploc). I did not rewrite my fork's master-branch for well-known problems when rewriting public histories.

For this new branch, I have created a new PR #118

**Pull request closed without merging**
