### PR TITLE
Fix bug: "invalid function count"

### PR DESCRIPTION
**Pull request by krzysiekpiasecki**
Statements 'use function' were counted as a function

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
This does not seem to take into account that `use` is also used for using traits.

**Comment by krzysiekpiasecki** [comment]
>> This does not seem to take into account that use is also used for using traits.

It doesn't.

```
    case T_TRAIT:
    if (!$this->isClassDeclaration($tokens, $i)) {
        continue
    }
```

**Comment by sebastianbergmann** [comment]
Can you add a test case, please? Thanks.

**Comment by krzysiekpiasecki** [comment]
Add to "source.php"  2 lines:

```php
1. use function time;
2.
```
Modified expectations:
llocGlobal +1
loc +2
lloc +1
ncloc +2

**Comment by krzysiekpiasecki** [comment]
Is it ok? Test passed.

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Pull request closed without merging**
